[package]
name = "deno_wry"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
rmp-serde = "1.3.0"
serde = { version="1.0.219", features=["derive"] }
winit = "0.30.12"
wry = "0.53.3"
